# Мы используем "3" так как это - самая свежая версия на момент написания этого кода.

version: '3'

# Следует учитывать, что docker-composes работает с сервисами.
# 1 сервис = 1 контейнер.
# Сервисом может быть клиент, сервер, приложение...
# Раздел, в котором будут описаны сервисы, начинается с 'services'.

services:

# собственно тип приложения
  app:
# build можно указать либо как строку, содержащую путь к контексту сборки, либо как объект с путем, указанным в контексте и, возможно, dockerfile и args.
    build: .
# Выставить порты. Укажите оба порта (HOST:CONTAINER)
    ports:
      - "5002:5002"
